[package]
name = "petri"
version = "0.1.0"
authors = ["Haydn Jones <haydnjonest@gmail.com", "Benjamin Mastripolitio <schwalegos@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst", branch = "main", features = ["optional"]}