[package]
name = "petri"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.6.0"
bytemuck = "1.7.3"
naga = "0.8.5"
bitflags = "1.3.2"
wgpu = "0.12.0"
crevice = "0.8.0"
rand = "0.8.4"
shaderc = "0.7.3"