[package]
name = "petri"
version = "0.1.0"
edition = "2018"
resolver = "2"

[lib]
name = "timing_macro"
path = "src/timing/macro.rs"

[[bin]]
name = "petri"
path = "src/main.rs"

[dependencies]
winit = "0.25.0"
wgpu = { version = "0.10.1", features = [ "spirv" ] }
bytemuck = { version = "1.7.2", features = [ "derive" ] }
fps_counter = "2.0.0"
rayon = "1.5.1"
wgpu-subscriber = "0.1.0"
rand = "0.8.4"
glam = { version = "0.18.0", features = [ "default", "mint" ] }
legion = "0.4.0"
shaderc = "0.7.3"
futures = "0.3.17"
egui = "0.14.2"
egui_wgpu_backend = "0.12.0"
egui_winit_platform = "0.10.0"
hdrhistogram = "*"
lazy_static = "1.4.0"
parking_lot = "*"
dashmap = "*"

[profile.dev.package."*"]
opt-level = 3