[package]
name = "petri"
version = "0.1.0"
authors = ["Haydn Jones <haydnjonest@gmail.com>", "Benjamin Mastripolitio <schwalegos@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.6.0-rc2"

gfx_core = "0.9.2"
gfx_device_gl = "0.16.2"

imgui = "0.7.0"
imgui-gfx-renderer = "0.7.0"
glam = { version = "0.17.3", features = ["mint"] }

[profile.release]
codegen-units = 1
lto = true