[package]
name = "petri"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.6.1"
bevy_egui = "0.11.1"
bytemuck = "1.7.3"
naga = "0.8.5"
bitflags = "1.3.2"
wgpu = "0.12.0"
crevice = "0.8.0"
rand = "0.8.5"
shaderc = "0.7.4"
rayon = "1.5.1"
jemallocator = "0.3.2"

[profile.release]
panic = "abort"
#lto = "fat"