[package]
name = "petri"
version = "0.1.0"
edition = "2021"

[dependencies]
####################
# GUI
####################
winit = "0.26.1"
wgpu = { version = "0.12.0", features = ["glsl"] }
naga = "0.8.3"
egui = "0.16.1"
egui_wgpu_backend = "0.16.0"
egui_winit_platform = "0.13.0"

####################
# Simulation
####################
bytemuck = { version = "1.13.0", features = [ "derive" ] }
fps_counter = "2.0.0"
rayon = "1.6.1"
wgpu-subscriber = "0.1.0"
rand = "0.8.5"
legion = "0.4.0"
futures = "0.3.25"
hdrhistogram = "7.5.2"
lazy_static = "1.4.0"
spin = { version = "0.9.4", features = ["rwlock", "default"]}
quanta = "0.10.1"
itertools = "0.10.5"
mimalloc = { version = "0.1.34", default-features = false }
ron = { version = "0.8.0", features = ["integer128"] }
serde = { version = "1.0.152", features = ["derive"] }
ultraviolet = { version = "0.9.0", features = ["serde", "mint", "int"]}

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"