[package]
name = "petri"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.26.0"
wgpu = { version = "0.12.0", features = ["glsl"] }
naga = "0.8.0"
bytemuck = { version = "1.7.3", features = [ "derive" ] }
fps_counter = "2.0.0"
rayon = "1.5.1"
wgpu-subscriber = "0.1.0"
rand = "0.8.4"
legion = "0.4.0"
futures = "0.3.19"
egui = "0.15.0"
egui_wgpu_backend = "0.15.0"
egui_winit_platform = "0.12.0"
hdrhistogram = "7.4.0"
lazy_static = "1.4.0"
spin = { version = "0.9.2", features = ["rwlock", "default"]}
quanta = "0.9.3"
itertools = "0.10.3"
mimalloc = { version = "0.1.27", default-features = false }
ron = "0.7.0"
serde = { version = "1.0.132", features = ["derive"] }
ultraviolet = { version = "0.8.1", features = ["serde", "mint", "int"]}

[profile.dev.package."*"]
opt-level = 3