[package]
name = "petri"
version = "0.1.0"
edition = "2021"

[dependencies]
####################
# GUI
####################
winit = "0.28.1"
wgpu = { version = "0.15.0", features = ["glsl"] }
naga = "0.11.0"
egui = "0.21.0"
egui-wgpu = "0.21.0"
egui-winit = "0.21.0"
num-format = "0.4.4"

####################
# Simulation
####################
bytemuck = { version = "1.13.0", features = [ "derive" ] }
fps_counter = "2.0.0"
rayon = "1.6.1"
rand = "0.8.5"
bevy_ecs = "0.9.1"
bevy_tasks = "0.9.1"
futures = "0.3.26"
hdrhistogram = "7.5.2"
lazy_static = "1.4.0"
spin = { version = "0.9.5", features = ["rwlock", "default"]}
quanta = "0.10.1"
itertools = "0.10.5"
ron = { version = "0.8.0", features = ["integer128"] }
serde = { version = "1.0.152", features = ["derive"] }
ultraviolet = { version = "0.9.0", features = ["serde", "int"]}

[profile.dev.package."*"]
opt-level = 3

#  Maximum optimization for release builds
[profile.release]
lto = "thin"
panic = "abort"
incremental = false